apiVersion: apps/v1
kind: Deployment
metadata:
  name: fenrir
  labels:
    desc: fenrir-app-development
spec:
  selector:
    matchLabels:
      app: fenrir
  replicas: 3
  template:
    metadata:
      labels:
        app: fenrir
    spec:
      containers:
      - name: fenrir-main
        image: docker.io/dockertraining007/docker-training:latest
        ports:
        - containerPort: 8000
